






controllers: {
  head_controller: {type: follow_controller, joints: [head_pan_joint, head_tilt_joint], action_name: head_controller/follow_joint_trajectory, onboard: False },
  arm_controller: {type: follow_controller, joints: [arm_lift_joint, arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_upperarm_roll_joint, arm_elbow_flex_joint, arm_wrist_flex_joint, arm_wrist_roll_joint], action_name: arm_controller/follow_joint_trajectory, onboard: False },
  # REX motors: 31750 cpr = 0.3888105m travel
  # D6/D7 - Left Encoder
  base_controller: {type: diff_controller, base_width: 0.381, ticks_meter: 81807, Kp: 15, Kd: 15, Ki: 0, Ko: 200, accel_limit: 1.0 },
  # A0 - Lift Encoder Counter
  # A5 - Lift Direction A (ROS D29)
  # A6 - Lift Direction B (ROS D30)
  # A7 - Lift PWM (ROS D31)
  # -329 at bottom of range, but causes trouble.
  # -313 = 15.625" from ground = 0.3960m - 0.0238m (ground clearance) - 0.1310 (base size z) = 0.242m
  # 0 = 33.875" from ground = 0.8604m
  # range: 0.4644
  arm_lift_controller: {type: linear_controller_i, joint: arm_lift_joint }
}

