(defpackage arbotix-srv
  (:use cl
        roslisp-msg-protocol)
  (:export
   "SETANGLE"
   "<SETANGLE-REQUEST>"
   "<SETANGLE-RESPONSE>"
   "SETDIGITAL"
   "<SETDIGITAL-REQUEST>"
   "<SETDIGITAL-RESPONSE>"
   "GETANALOG"
   "<GETANALOG-REQUEST>"
   "<GETANALOG-RESPONSE>"
   "SETJOINTS"
   "<SETJOINTS-REQUEST>"
   "<SETJOINTS-RESPONSE>"
   "RELAX"
   "<RELAX-REQUEST>"
   "<RELAX-RESPONSE>"
   "GETANGLE"
   "<GETANGLE-REQUEST>"
   "<GETANGLE-RESPONSE>"
   "GETDIGITAL"
   "<GETDIGITAL-REQUEST>"
   "<GETDIGITAL-RESPONSE>"
   "ISMOVING"
   "<ISMOVING-REQUEST>"
   "<ISMOVING-RESPONSE>"
   "GETVOLTAGE"
   "<GETVOLTAGE-REQUEST>"
   "<GETVOLTAGE-RESPONSE>"
  ))

