obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.21, 0.21], [0.21, -0.21], [-0.21, -0.21], [-0.21, 0.21]]
#footprint_inflation: 0.01
robot_radius: 0.22
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

